### PR TITLE
Added option to mark public compiler generated types.

### PR DESCRIPTION
**Pull request by aronmek**

### CODE REVIEW

**Comment by SimonCropp** [comment]
Can u add a test that verifies this change

**Comment by aronmek** [comment]
Done

**Comment by SimonCropp** [comment]
Looks good. Can u add some doco in the readme. Then i can release

**Comment by aronmek** [comment]
@SimonCropp Done

**Comment by SimonCropp** [comment]
this should now be deployed pending a nuget update

**Pull request merged**
